src/Entity/SecondHandCar.php
<?php

namespace App\Entity;

use App\Repository\SecondHandCarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Expr\Cast\Array_;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Flex\Response as FlexResponse;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: SecondHandCarRepository::class)]
class SecondHandCar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $reference = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: 2)]
    #[Assert\Range(min: 0, max: 100000000)]
    private ?string $price = null;

    #[ORM\Column]
    #[Assert\Range(min: 0, max: 3000000)]
    private ?int $kilometers = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $circulation_year = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    #[Assert\Range(min: 1, max: 40)]
    private ?int $fiscal_power = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    #[Assert\Range(min: 1, max: 2500)]
    private ?int $din_power = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $doors = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $seats = null;

    #[ORM\Column]
    private ?bool $auto_gear_box = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $critair_nb = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $create_date = null;

    #[ORM\ManyToOne(inversedBy: 'secondHandCars', targetEntity: User::class)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'vehicle')]
    #[ORM\JoinColumn(nullable: true)]
    #[Assert\NotBlank()]
    private ?Type $type = null;

    #[ORM\ManyToOne(inversedBy: 'vehicle')]
    #[ORM\JoinColumn(nullable: true)]
    #[Assert\NotBlank()]
    private ?Model $model = null;

    #[ORM\OneToMany(mappedBy: 'vehicle', targetEntity: Galery::class)]
    private Collection $galeries;

    #[ORM\ManyToMany(targetEntity: Color::class, inversedBy: 'secondHandCars')]
    private Collection $color;

    #[ORM\ManyToMany(targetEntity: Energy::class, inversedBy: 'secondHandCars')]
    private Collection $energies;

    #[ORM\ManyToMany(targetEntity: Equipments::class, inversedBy: 'secondHandCars')]
    private Collection $equipments;

    #[ORM\ManyToMany(targetEntity: Options::class, inversedBy: 'secondHandCars')]
    private Collection $options;

    public function __construct()
    {
        $this->galeries = new ArrayCollection();
        $this->color = new ArrayCollection();
        $this->energies = new ArrayCollection();
        $this->equipments = new ArrayCollection();
        $this->options = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getId();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getKilometers(): ?int
    {
        return $this->kilometers;
    }

    public function setKilometers(int $kilometers): static
    {
        $this->kilometers = $kilometers;

        return $this;
    }

    public function getCirculationYear(): ?\DateTimeInterface
    {
        return $this->circulation_year;
    }

    public function setCirculationYear(\DateTimeInterface $circulation_year): static
    {
        $this->circulation_year = $circulation_year;

        return $this;
    }

    public function getFiscalPower(): ?int
    {
        return $this->fiscal_power;
    }

    public function setFiscalPower(?int $fiscal_power): static
    {
        $this->fiscal_power = $fiscal_power;

        return $this;
    }

    public function getDinPower(): ?int
    {
        return $this->din_power;
    }

    public function setDinPower(?int $din_power): static
    {
        $this->din_power = $din_power;

        return $this;
    }

    public function getDoors(): ?int
    {
        return $this->doors;
    }

    public function setDoors(int $doors): static
    {
        $this->doors = $doors;

        return $this;
    }

    public function getSeats(): ?int
    {
        return $this->seats;
    }

    public function setSeats(int $seats): static
    {
        $this->seats = $seats;

        return $this;
    }

    public function isAutoGearBox(): ?bool
    {
        return $this->auto_gear_box;
    }

    public function setAutoGearBox(bool $auto_gear_box): static
    {
        $this->auto_gear_box = $auto_gear_box;

        return $this;
    }

    public function getCritairNb(): ?int
    {
        return $this->critair_nb;
    }

    public function setCritairNb(?int $critair_nb): static
    {
        $this->critair_nb = $critair_nb;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): static
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }


    public function getModel(): ?Model
    {
        return $this->model;
    }

    public function setModel(?Model $model): static
    {
        $this->model = $model;

        return $this;
    }

    /**
     * @return Collection<int, Galery>
     */
    public function getGaleries(): Collection
    {
        return $this->galeries;
    }

    public function addGalery(Galery $galery): static
    {
        if (!$this->galeries->contains($galery)) {
            $this->galeries->add($galery);
            $galery->setVehicle($this);
        }

        return $this;
    }

    public function removeGalery(Galery $galery): static
    {
        if ($this->galeries->removeElement($galery)) {
            // set the owning side to null (unless already changed)
            if ($galery->getVehicle() === $this) {
                $galery->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Color>
     */
    public function getColor(): Collection
    {
        return $this->color;
    }

    public function addColor(Color $color): static
    {
        if (!$this->color->contains($color)) {
            $this->color->add($color);
        }

        return $this;
    }

    public function removeColor(Color $color): static
    {
        $this->color->removeElement($color);

        return $this;
    }

    public function showColors(SecondHandCarRepository $secondHandCarRepository, int $id): Array
    {
        $secondHanCar = $secondHandCarRepository->findOneByIdJoinedToColor($id);
        $colorsCar=[];
        if ($secondHanCar){
            $colors = $secondHanCar->getColor();
            foreach ($colors as $color){
                $colorsCar[]= $color->getColor();
            }
        }
        return $colorsCar;
    }

    /**
     * @return Collection<int, Energy>
     */
    public function getEnergies(): Collection
    {
        return $this->energies;
    }

    public function addEnergy(Energy $energy): static
    {
        if (!$this->energies->contains($energy)) {
            $this->energies->add($energy);
        }

        return $this;
    }

    public function removeEnergy(Energy $energy): static
    {
        $this->energies->removeElement($energy);

        return $this;
    }

    public function showEnergies(SecondHandCarRepository $secondHandCarRepository, int $id): Array
    {
        $secondHanCar = $secondHandCarRepository->findOneByIdJoinedToEnergy($id);
        $energiesCar=[];
        if ($secondHanCar){
            $energies = $secondHanCar->getEnergies();
            foreach ($energies as $energy){
                $energiesCar[]= $energy->getEnergy();
            }
        }
        return $energiesCar;
    }

    /**
     * @return Collection<int, Equipments>
     */
    public function getEquipments(): Collection
    {
        return $this->equipments;
    }

    public function addEquipment(Equipments $equipment): static
    {
        if (!$this->equipments->contains($equipment)) {
            $this->equipments->add($equipment);
        }

        return $this;
    }

    public function removeEquipment(Equipments $equipment): static
    {
        $this->equipments->removeElement($equipment);

        return $this;
    }

    public function showEquipments(SecondHandCarRepository $secondHandCarRepository, int $id): Array
    {
        $secondHanCar = $secondHandCarRepository->findOneByIdJoinedToEquipments($id);
        $equipmentsCar=[];
        if ($secondHanCar){
            $equipments = $secondHanCar->getEquipments();
            foreach ($equipments as $equipment){
                $equipmentsCar[]= $equipment->getEquipment();
            }
        }
        return $equipmentsCar;
    }

    /**
     * @return Collection<int, Options>
     */

templates/advert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Annouces de Véhicules d'occasion {% endblock %}

{% block body %}
    
    <form class="row flex-row justify-content-center">
        <div class="col-3 m-3">
            <h5>kilométrage :</h5>
                <input name="kmMin" value="{{kmMinCar}}" min="0" max="{{kmMaxCar}}" placeholder="Minimum"><br>
                <input name="kmMax" value="{{kmMaxCar}}" min="{{kmMinCar}}" max="1000000"  placeholder="Maximum">
        </div>
        <div class="col-3 m-3">
            <h5>Prix :</h5>
                <input name="priceMin" value="{{priceMinCar}}" min="0" max="{{priceMaxCar}}" placeholder="Minimum"><br>
                <input name="priceMax" value="{{priceMaxCar}}" min="{{priceMinCar}}" max="1000000" placeholder="Maximum">
        </div>
        <div class="col-3 m-3">
            <h5>Années :</h5>
                <input name="yearMin"  value="{{yearMinCar}}" min="{{yearMinCar}}" max="{{yearMaxCar}}" placeholder="Minimum" ><br>
                <input name="yearMax"  value="{{yearMaxCar}}" min="{{yearMinCar}}" max="{{yearMaxCar}}" placeholder="Maximum">
        </div>
        <input type="submit" class= "col-3" value="Filtrer">
    </form>
    
    <div class="row flex-row justify-content-center">
        {% for secondHandCar in secondHandCars %}
            {% include 'partials/advert/_advert_list.html.twig' %}
        {% endfor %}
    </div>

{% endblock %}

templates/advert/showOneCar.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{secondHandCar.model.brand}} {{secondHandCar.model}} {% endblock %}

{% block body %}
    <div class="row flex-row">
        {% if (photos|length > 0) %}
            <div class="col-12 col-lg-7">
                <div id="carouselPhotos" class="carousel slide justify-content-center m-3">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselPhotos" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselPhotos" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselPhotos" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                        <div class="carousel-inner">
                            {% if (photos[0]) %}
                                <div class="carousel-item active">
                                    <img src="{{photoPath ~ photos[0].imageName}}" class="card-img-top" alt="1ère photo de {{secondHandCar.model.brand}} {{secondHandCar.model}}">  
                                </div>
                            {% endif %}
                            {% if (photos|length >1 and photos[1])%} 
                                <div class="carousel-item">
                                    <img src="{{photoPath ~ photos[1].imageName}}" class="card-img-top" alt="2ème photo de {{secondHandCar.model.brand}} {{secondHandCar.model}}">  
                                </div>
                            {% endif %} 
                            {% if (photos|length >2 and photos[2])%}
                                <div class="carousel-item">
                                    <img src="{{photoPath ~ photos[2].imageName}}" class="card-img-top" alt="3ème photo de {{secondHandCar.model.brand}} {{secondHandCar.model}}">  
                                </div>
                            {% endif %}
                        </div>
                    {% if (photos|length >1 and photos[1])%}     
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselPhotos" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselPhotos" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <div class="col-12 col-lg-7">
                <img src="{{photoPath ~ 'DefaultCar.png'}}" class="card-img-top m-5 w-75" alt="photo de {{secondHandCar.model.brand}} {{secondHandCar.model}} absente">  
            </div>
        {% endif %}
        <div class="card ms-4 ms-md-5 ms-lg-2 mt-3 mb-2 col-10 col-md-5 col-lg-2">
            <div class="card-body flex-row">
                <div class="col">
                    <h3 class="card-title">{{secondHandCar.model.brand}} {{secondHandCar.model}}</h3>
                    <h4>{% if (secondHandCar.reference) %}Référence de l'annonce : {{secondHandCar.reference}}{% endif %}</h4>
                    <p class="card-text">
                        <h4> Prix : {{secondHandCar.price}} €</h4>
                        <hr>
                        {% if (secondHandCar.type) %} Type : {{secondHandCar.type}} <br>{% endif %}
                        {% if (colors|length > 0) %}
                            <p> Couleurs :
                            {% for color in colors %}
                                {{color -}} 
                            {% endfor %}  
                            <hr>
                            </p>
                        {% endif %}
                        <p>
                        {% if (secondHandCar.CirculationYear) %} Mise en circulation : {{secondHandCar.CirculationYear.format("d/m/Y")}}<br>{% endif %} 
                        {% if (secondHandCar.kilometers) %}km : {{secondHandCar.kilometers}}<br>{% endif %}
                        {% if (secondHandCar.fiscalPower) %} Puissance Fiscale : {{secondHandCar.fiscalPower}} CV <br> {% endif %}
                        {% if (secondHandCar.dinPower) %} Puissance DIN : {{secondHandCar.dinPower}} CV <br>{% endif %}
                        </p>
                        <p>
                        {% if (energies|length > 0) %}
                            Energies :
                            {% for energy in energies %}
                                {{energy -}} 
                            {% endfor %} 
                            <br>  
                        {% endif %}
                        {% if (secondHandCar.autoGearBox) %} Boîte automatique <br>{% endif %}
                        </p>
                        <p>
                        {% if (secondHandCar.doors) %} Nombres de portes : {{secondHandCar.doors}} <br>{% endif %}
                        {% if (secondHandCar.seats) %} Nombres de places : {{secondHandCar.seats}}<br> {% endif %}
                        {% if (secondHandCar.critairNb) %} Crit'air : {{secondHandCar.critairNb}}<br> {% endif %}
                        </p>
                        
                    </p>
                </div>
            </div>
        </div>
        <div class="card ms-4 ms-md-3 ms-lg-2 mt-3 mb-2 col-10 col-md-5 col-lg-2">
            <div class="card-body flex-row">
                <div class="col">
                    {% if (equipments|length > 0) %}
                        <div class="col">
                            <h4 class="card-title">Equipements</h4>
                            <p class="card-text">
                                {% for equipement in equipments %}
                                    {{equipement }} <br>
                                {% endfor %}  
                                <hr>
                            </p>
                        </div>
                    {% endif %}
                    {% if (options|length > 0) %}
                        <div class="col">
                            <h4 class="card-title">Options</h4>
                            <p class="card-text">
                                {% for option in options %}
                                    {{option }} <br>
                                {% endfor %}  
                            <br>
                            </p>
                        </div>
                    {% endif %}
                    <div class="card-footer">
                        <strong> {{infos.5.title}}</strong>
                        {{infos.5.content|raw}}
                        <a href="{{ path('app_contact',{'ref': secondHandCar.id ~ secondHandCar.model.brand ~ secondHandCar.model })}}" class="btn btn-primary">Formulaire de contact</a>
                    </div>
                </div>
        </div>
    </div>
    
{% endblock %}